=== Servilat/JavaLabs/personsScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="persons">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="person" type="Person" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Person">
    <xs:sequence>
      <xs:element name="basicInformation">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" type="Name"/>
          </xs:sequence>
          <xs:attribute name="birthday" type="xs:date" use="required"/>
          <xs:attribute name="sex" type="Sex" use="required"/>
          <xs:attribute name="heigth" type="xs:float"/>
          <xs:attribute name="weigth" type="xs:float"/>
        </xs:complexType>
      </xs:element>
      <xs:element name="contactInformation" type="ContactInfo"/>
      <xs:element name="works" type="Works"/>
    </xs:sequence>
    <xs:attribute name="ID" type="PassportID" use="required"/>
  </xs:complexType>
  <xs:complexType name="ContactInfo">
    <xs:sequence>
      <xs:element name="mobilePhone">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,15}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="homePhone">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1,15}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="address" type="Address"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Address">
    <xs:attribute name="country" type="string" use="required"/>
    <xs:attribute name="city" type="string" use="required"/>
    <xs:attribute name="street" type="string" use="required"/>
    <xs:attribute name="house" type="xs:integer"/>
  </xs:complexType>
  <xs:complexType name="Works">
    <xs:sequence>
      <xs:element name="work" type="Work" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Name">
    <xs:attribute name="lastName" type="string" use="required"/>
    <xs:attribute name="firstName" type="string" use="required"/>
    <xs:attribute name="middleName" type="string" use="required"/>
  </xs:complexType>
  <xs:complexType name="Work">
    <xs:attribute name="company" type="string"/>
    <xs:attribute name="position" type="string"/>
    <xs:attribute name="experience" type="xs:integer"/>
  </xs:complexType>
  <xs:simpleType name="PassportID">
    <xs:restriction base="xs:ID">
      <xs:length value="15"/>
      <xs:pattern value="[A-Z0-9]{15}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Sex">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Female"/>
      <xs:enumeration value="Male"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="string">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z]{2,}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Servilat/JavaLabs/persons.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="file:///D:/Projects.%20Java/JavaLabs/personsScheme.xsd">
    <person ID="AAAAA33433666HH">
        <basicInformation birthday="1955-04-27" sex="Male">
            <name firstName="Nikita" lastName="Romanyk" middleName="Konstantinovich"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>7890</mobilePhone>
            <homePhone>7890</homePhone>
            <address city="Warsawa" country="Poland" house="8" street="Kostyshki"/>
        </contactInformation>
        <jobs>
            <job company="Swankeys" experience="2" position="CIO"/>
        </jobs>
    </person>
    <person ID="D4RT45TY7JHGUIR">
        <basicInformation birthday="1998-06-30" sex="Male">
            <name firstName="Kirill" lastName="Petrov" middleName="Vasil"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>4548646</mobilePhone>
            <homePhone>456729386</homePhone>
            <address city="Minsk" country="Belarus" house="6" street="Pushkina"/>
        </contactInformation>
        <jobs>
            <job company="qwer" experience="3" position="qwer"/>
        </jobs>
    </person>
    <person ID="D4RT45TY7JHGOIR">
        <basicInformation birthday="1998-10-17" sex="Male">
            <name firstName="Kirill" lastName="Petrov" middleName="Vasil"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>4548646</mobilePhone>
            <homePhone>456729386</homePhone>
            <address city="Minsk" country="Belarus" house="6" street="Pushkina"/>
        </contactInformation>
        <jobs>
            <job company="qwer" experience="3" position="qwer"/>
        </jobs>
    </person>
    <person ID="EERT5TY678UT654">
        <basicInformation birthday="1954-12-04" sex="Male">
            <name firstName="Zubko" lastName="Evgensd" middleName="Vital"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>234523452333333</mobilePhone>
            <homePhone>45235236</homePhone>
            <address city="ete" country="ery" house="54" street="ggg"/>
        </contactInformation>
        <jobs/>
    </person>
    <person ID="EERT5TY678UT655">
        <basicInformation birthday="1954-12-04" sex="Male">
            <name firstName="Zubko" lastName="Evgen" middleName="Vital"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>234523452</mobilePhone>
            <homePhone>45235236</homePhone>
            <address city="ete" country="ery" house="54" street="56"/>
        </contactInformation>
        <jobs>
            <job company="wetwet" experience="33" position="ewtwet"/>
            <job company="ter" experience="65" position="ry"/>
            <job company="rjrjujuy" experience="46" position="fgkjhdds"/>
        </jobs>
    </person>
    <person ID="ERTTTTTTTTTTTTT">
        <basicInformation birthday="1952-01-02" sex="Male">
            <name firstName="rtyery" lastName="eryr" middleName="eryery"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>6346</mobilePhone>
            <homePhone>546356</homePhone>
            <address city="eryerery" country="wtyer" house="55" street="eryer"/>
        </contactInformation>
        <jobs/>
    </person>
    <person ID="WETWETEWRTWERTW">
        <basicInformation birthday="1953-02-03" sex="Male">
            <name firstName="twett" lastName="wetwet" middleName="ewrtwret"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>45634634</mobilePhone>
            <homePhone>5526346</homePhone>
            <address city="wetwe" country="wert" house="43" street="wt"/>
        </contactInformation>
        <jobs/>
    </person>
    <person ID="H56U47G5867R6YE">
        <basicInformation birthday="1952-04-02" sex="Male">
            <name firstName="rurt" lastName="adfhfdj" middleName="rtyueuw"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>64274574</mobilePhone>
            <homePhone>4634765484</homePhone>
            <address city="yery" country="erye" house="65" street="yerye"/>
        </contactInformation>
        <jobs/>
    </person>
    <person ID="RG0G234G02KT394">
        <basicInformation birthday="1997-01-02" sex="Male">
            <name firstName="Vale" lastName="Abba" middleName="Fuko"/>
        </basicInformation>
        <contactInformation>
            <mobilePhone>923403505536</mobilePhone>
            <homePhone>2345235</homePhone>
            <address city="EAFkla" country="AJjdsaj" house="45" street="kmASD"/>
        </contactInformation>
        <jobs/>
    </person>
</persons>

=== Servilat/JavaLabs/~persons.xml
<?xml version="1.0" encoding="UTF-8"?>
<persons xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/Projects.%20Java/JavaLabs/personsScheme.xsd">
	<person ID="AAAAA33333666HH">
		<basicInformation sex="Male" birthday="1998-12-02">
			<name lastName="Zubko" firstName="Evgen" middleName="Vital"/>
		</basicInformation>
		<contactInfo>
			<mobilePhone>1234</mobilePhone>
			<homePhone>1234</homePhone>
			<address country="BY" city="Minsk" street="Kolasa" house="28"/>
		</contactInfo>
		<works>
			<work company="Itransition" position="Manager" experience="2"/>
			<work company="BSUIR" position="Student" experience="5"/>
		</works>
	</person>
	<person ID="AAAAA33433666HH">
		<basicInformation sex="Female" birthday="1989-02-22">
			<name lastName="Harkavik" firstName="Evgeniy" middleName="Antonovich"/>
		</basicInformation>
		<contactInfo>
			<mobilePhone>4321</mobilePhone>
			<homePhone>4321</homePhone>
			<address country="USA" city="LA" street="Pushkina" house="1"/>
		</contactInfo>
		<works>
			<work company="Google" position="Director" experience="10"/>
			<work company="Yandex" position="Manager" experience="3"/>
			<work company="Sosedi" position="Prodavec" experience="4"/>
		</works>
	</person>
	<person ID="AAAAA3HN33666HH">
		<basicInformation sex="Male" birthday="1965-12-03">
			<name lastName="Busko" firstName="Yauheni" middleName="Aleksandrovich"/>
		</basicInformation>
		<contactInfo>
			<mobilePhone>7788</mobilePhone>
			<homePhone>8880</homePhone>
			<address country="Britain" city="London" street="Koroleva" house="5"/>
		</contactInfo>
		<works>
			<work company="Swankeys" position="CEO" experience="10"/>
		</works>
	</person>
	<person ID="AAAAA33335666HH">
		<basicInformation sex="Female" birthday="1955-04-27">
			<name lastName="Romanyk" firstName="Nikita" middleName="Konstantinovich"/>
		</basicInformation>
		<contactInfo>
			<mobilePhone>7890</mobilePhone>
			<homePhone>7890</homePhone>
			<address country="Poland" city="Warsawa" street="Kostyshki" house="8"/>
		</contactInfo>
		<works>
			<work company="Swankeys" position="CIO" experience="2"/>
		</works>
	</person>
</persons>
